{% set version = "0.3.7" %}

package:
  name: fs_filepicker
  version: {{ version }}

source:
  url: https://github.com/open-mss/fs_filepicker/archive/{{ version }}.tar.gz
  sha256: 27c1faad8ecee48a507b626b2caac6181e9bf5019d96d83de4932051bf125798

build:
  number: 5
  noarch: python
  entry_points:
    - fs_filepicker = fslib.fs_filepicker:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.6
    - pip
    - future
  run:
    - python >=3.6
    - pyqt
    - humanfriendly
    - fs
    - fs.webdavfs
    - fs.sshfs
    - future

test:
  imports:
    - fslib.fs_filepicker
  commands:
    - fs_filepicker -h

about:
  home: https://github.com/open-mss/fs_filepicker
  license:  Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: QT file picker (Open|Save|GetDirectory) for accessing a pyfilesystem2
  dev_url: https://github.com/open-mss/fs_filepicker

extra:
  recipe-maintainers:
    - ReimarBauer
