{% set version = "0.3.9" %}
{% set python_min = "3.10" %}

package:
  name: fs_filepicker
  version: {{ version }}

source:
  url: https://github.com/open-mss/fs_filepicker/archive/{{ version }}.tar.gz
  sha256: 58bcb8e6003997fca5101b0a12c7e169511fa012eb7464e8ea360ad7d89bc73c

build:
  number: 0
  noarch: python
  entry_points:
    - fs_filepicker = fslib.fs_filepicker:main
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python >={{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pyqt >=5, <6
    - qt >=5.10, <6
    - humanfriendly
    - fs
    - fs.webdavfs
    - fs.sshfs

test:
  requires:
    - python >={{ python_min }}
  imports:
    - fslib.fs_filepicker
  commands:
    - fs_filepicker -h

about:
  home: https://github.com/open-mss/fs_filepicker
  license:  Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: QT file picker (Open|Save|GetDirectory) for accessing a pyfilesystem2
  dev_url: https://github.com/open-mss/fs_filepicker

extra:
  recipe-maintainers:
    - ReimarBauer
