{% set name = "fs_filepicker" %}
{% set version = "0.3.7" %}
{% set sha256 = "27c1faad8ecee48a507b626b2caac6181e9bf5019d96d83de4932051bf125798" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/ReimarBauer/fs_filepicker/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 2
  entry_points:
    - fs_filepicker = fslib.fs_filepicker:main
  script: python -m pip install --no-deps --single-version-externally-managed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - future

  run:
    - python
    - pyqt 5.*
    - humanfriendly
    - fs
    - fs.webdavfs
    - fs.sshfs
    - future

test:
  imports:
    - fslib.fs_filepicker
  commands:
    - fs_filepicker -h

about:
  home: https://github.com/ReimarBauer/fs_filepicker
  license: "Apache 2.0"
  license_family: "APACHE"
  license_file: LICENSE
  summary: 'QT file picker (Open|Save|GetDirectory) for accessing a pyfilesystem2'
  dev_url: https://github.com/ReimarBauer/fs_filepicker

extra:
  recipe-maintainers:
    - ReimarBauer
